name: Deploy Slack Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to EC2 and run script
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/work-clock
            git pull origin main
            
            echo "${{ secrets.ENV_FILE }}" > .env
            echo ".env 파일 생성 완료"
            
            # 실행 권한 부여
            chmod +x start_bot.sh

            # 봇 실행
            ./start_bot.sh
